### ISSUE TITLE
No API to update application custom attributes

### ISSUE THREAD

**Issue by mperumalswamy** [SAP-docs/btp-cloud-identity-services#37]
Is an API missing or it doesn't exist yet?

https://help.sap.com/docs/cloud-identity-services/cloud-identity-services/user-management-rest-api?locale=en-US

**Comment by ValAta** [comment]
Hi @mperumalswamy,
Thanks for your question. Could you please clarify what do you mean by custom attributes here and if possible give an example?
BR,
Valentin

**Comment by mperumalswamy** [comment]
Hi @ValAta 
In the PUT API from help page which I mentioned is not in api.sap.com. Then this API can be used to update different fields/attributes of IAS actually but only status attribute is mentioned in the documentation. I would also be happy to give a PR with the improvements.

**Comment by ValAta** [comment]
Hi @mperumalswamy, 
Thanks for the clarification. You can update the different user attributes via the https://api.sap.com/api/IdDS_SCIM/path/updateUser api. Have you already checked it?
The API that you have commented is for the deactivation of an SP (service provider) user, that's why it contains the status attribute  with its values active and inactive.
BR

**Comment by mperumalswamy** [comment]
Hi @ValAta , we would like to update the spCustomAttributes. So the current PUT API which I mentioned should also work for it. Correct?

**Comment by ValAta** [comment]
Hi @mperumalswamy , the PUT [SP User Deactivation](https://help.sap.com/docs/cloud-identity-services/cloud-identity-services/sp-user-deactivation?version=Cloud) is only for the update of the status attribute, and not for other attributes.
BR,
